- name: Deploy a web application
  hosts: web
  tasks:
    - name: install python dependencies
      package:
        name:
        - python3
        - python3-setuptools
        - python3-dev
        - python3-pip
        - build-essential
        - python3-mysqldb
        update_cache: yes
    
    - name: install mysql packages
      package:
        name:
        - mysql-server
        - mysql-client
        update_cache: yes
    
    - name: Start mysql service
      shell: service mysql start

    - include: tasks/deploy_db.yml
    - include: tasks/deploy_web.yml
      

