- name: install python dependencies
  package:
    name:
    - python3
    - python3-setuptools
    - python3-dev
    - python3-pip
    - build-essential
    - python3-mysqldb
    update_cache: yes

- name: install mysql packages
  package:
    name:
    - mysql-server
    - mysql-client
    update_cache: yes