- name: Start mysql service
  shell: service mysql start

- name: Create application database
  mysql_db:
    check_implicit_admin: true
    name: employee_db
    login_host: localhost
    login_user: root
    login_password: Passw0rd
    login_unix_socket:  /var/run/mysqld/mysqld.sock
    state: present

- name: Create a table in the MySQL database
  mysql_query:
    login_user: root
    login_host: localhost
    login_password: "{{ db_user_password }}"
    login_unix_socket:  /var/run/mysqld/mysqld.sock
    login_db: "{{ db_name }}"
    query: 
    - "CREATE TABLE IF NOT EXISTS employees (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255));"
    - "INSERT INTO employees(name) VALUES ('HAB');"

- name: Create Dabase User
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_user_password }}"
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: '%'